name: heimanmanga
description: A manga reading application.
version: 0.1.15+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cached_network_image: ^3.3.0
  # Web optimizations
  flutter_web_plugins:
    sdk: flutter
  url_launcher: ^6.2.2
  shared_preferences: ^2.2.2
  package_info_plus: ^4.2.0
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.3
  path_provider: ^2.1.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.0
  drift_dev: ^2.15.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon_draft.png"

flutter:
  uses-material-design: true
  # Web-specific configuration
  generate: true

  assets:
    - assets/app_icon_draft.png
